### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by GinMitch** [cscart/sdk#4]
Composer throws the following error when trying to install SDK:
`cscart/sdk v1.1.2 requires cscart/upgrade-builder ~1.0 -> no matching package found`

Please create a release for `cscart/upgrade-builder` and submit it to Packagist to resolve the dependency issue.

Also, update SDK's installation section in [the readme file](https://github.com/cscart/sdk/blob/c41bbaa91d85df4bdf865ca733990db6e768b557/README.md#installing):
```bash
composer global require cscart/sdk
```

**Comment by torunar** [comment]
Hello @mullinsmikey!

Sorry for the delay, it took me some time to resolve the maintaining issue with the SDK package on Packagist. 
Fortunately, the `cscart/upgrade-builder` package was added to Packagist and SDK can be properly installed via composer now.

https://github.com/cscart/upgrade-builder/releases/tag/v1.0.0
https://github.com/cscart/sdk/releases/tag/v1.1.3
