### ISSUE TITLE
Не запускается sdk

### ISSUE THREAD

**Issue by msoloveva** [cscart/sdk#5]
При выполении команды composer global require "cscart/sdk:*" возникают конфликты. 
Скорее всего проблема в composer.json. Мое окружение: линукс, php72, composer2.0. Ошибка:
Changed current directory to /home/msoloveva/.config/composer
./composer.json has been updated
Running composer update cscart/sdk --with-dependencies
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - deployer/phar-update v2.2.0 requires symfony/console ~2.7|~3.0|~4.0|~5.0 -> satisfiable by symfony/console[v3.0.0, ..., v3.4.47].
    - symfony/yaml v5.1.5 conflicts with symfony/console v3.4.47.
    - symfony/yaml v5.1.5 conflicts with symfony/console v3.4.46.
    - symfony/yaml v5.1.5 conflicts with symfony/console v3.4.45.
    - symfony/yaml v5.1.5 conflicts with symfony/console v3.4.44.
    - symfony/yaml v5.1.5 conflicts with symfony/console v3.4.43.
    - symfony/yaml v5.1.5 conflicts with symfony/console v3.4.42.
    - symfony/yaml v5.1.5 conflicts with symfony/console v3.4.41.
    - symfony/yaml v5.1.5 conflicts with symfony/console v3.4.40.
    - symfony/yaml v5.1.5 conflicts with symfony/console v3.4.39.
    - symfony/yaml v5.1.5 conflicts with symfony/console v3.4.38.
    - symfony/yaml v5.1.5 conflicts with symfony/console v3.4.37.
    - symfony/yaml v5.1.5 conflicts with symfony/console v3.4.36.
    - symfony/yaml v5.1.5 conflicts with symfony/console v3.4.35.
    - symfony/yaml v5.1.5 conflicts with symfony/console v3.4.34.
    - symfony/yaml v5.1.5 conflicts with symfony/console v3.4.33.
    - symfony/yaml v5.1.5 conflicts with symfony/console v3.4.32.
    - symfony/yaml v5.1.5 conflicts with symfony/console v3.4.31.
    - symfony/yaml v5.1.5 conflicts with symfony/console v3.4.30.
    - symfony/yaml v5.1.5 conflicts with symfony/console v3.4.29.
    - symfony/yaml v5.1.5 conflicts with symfony/console v3.4.28.
    - symfony/yaml v5.1.5 conflicts with symfony/console v3.4.27.
    - symfony/yaml v5.1.5 conflicts with symfony/console v3.4.26.
    - symfony/yaml v5.1.5 conflicts with symfony/console v3.4.25.
    - symfony/yaml v5.1.5 conflicts with symfony/console v3.4.24.
    - symfony/yaml v5.1.5 conflicts with symfony/console v3.4.23.
    - symfony/yaml v5.1.5 conflicts with symfony/console v3.4.22.
    - symfony/yaml v5.1.5 conflicts with symfony/console v3.4.21.
    - symfony/yaml v5.1.5 conflicts with symfony/console v3.4.20.
    - symfony/yaml v5.1.5 conflicts with symfony/console v3.4.19.
    - symfony/yaml v5.1.5 conflicts with symfony/console v3.4.18.
    - symfony/yaml v5.1.5 conflicts with symfony/console v3.4.17.
    - symfony/yaml v5.1.5 conflicts with symfony/console v3.4.16.
    - symfony/yaml v5.1.5 conflicts with symfony/console v3.4.15.
    - symfony/yaml v5.1.5 conflicts with symfony/console v3.4.14.
    - symfony/yaml v5.1.5 conflicts with symfony/console v3.4.13.
    - symfony/yaml v5.1.5 conflicts with symfony/console v3.4.12.
    - symfony/yaml v5.1.5 conflicts with symfony/console v3.4.11.
    - symfony/yaml v5.1.5 conflicts with symfony/console v3.4.10.
    - symfony/yaml v5.1.5 conflicts with symfony/console v3.4.9.
    - symfony/yaml v5.1.5 conflicts with symfony/console v3.4.8.
    - symfony/yaml v5.1.5 conflicts with symfony/console v3.4.7.
    - symfony/yaml v5.1.5 conflicts with symfony/console v3.4.6.
    - symfony/yaml v5.1.5 conflicts with symfony/console v3.4.5.
    - symfony/yaml v5.1.5 conflicts with symfony/console v3.4.4.
    - symfony/yaml v5.1.5 conflicts with symfony/console v3.4.3.
    - symfony/yaml v5.1.5 conflicts with symfony/console v3.4.2.
    - symfony/yaml v5.1.5 conflicts with symfony/console v3.4.1.
    - symfony/yaml v5.1.5 conflicts with symfony/console v3.4.0.
    - symfony/yaml v5.1.5 conflicts with symfony/console v3.3.18.
    - symfony/yaml v5.1.5 conflicts with symfony/console v3.3.17.
    - symfony/yaml v5.1.5 conflicts with symfony/console v3.3.16.
    - symfony/yaml v5.1.5 conflicts with symfony/console v3.3.15.
    - symfony/yaml v5.1.5 conflicts with symfony/console v3.3.14.
    - symfony/yaml v5.1.5 conflicts with symfony/console v3.3.13.
    - symfony/yaml v5.1.5 conflicts with symfony/console v3.3.12.
    - symfony/yaml v5.1.5 conflicts with symfony/console v3.3.11.
    - symfony/yaml v5.1.5 conflicts with symfony/console v3.3.10.
    - symfony/yaml v5.1.5 conflicts with symfony/console v3.3.9.
    - symfony/yaml v5.1.5 conflicts with symfony/console v3.3.8.
    - symfony/yaml v5.1.5 conflicts with symfony/console v3.3.7.
    - symfony/yaml v5.1.5 conflicts with symfony/console v3.3.6.
    - symfony/yaml v5.1.5 conflicts with symfony/console v3.3.5.
    - symfony/yaml v5.1.5 conflicts with symfony/console v3.3.4.
    - symfony/yaml v5.1.5 conflicts with symfony/console v3.3.3.
    - symfony/yaml v5.1.5 conflicts with symfony/console v3.3.2.
    - symfony/yaml v5.1.5 conflicts with symfony/console v3.3.1.
    - symfony/yaml v5.1.5 conflicts with symfony/console v3.3.0.
    - symfony/yaml v5.1.5 conflicts with symfony/console v3.2.14.
    - symfony/yaml v5.1.5 conflicts with symfony/console v3.2.13.
    - symfony/yaml v5.1.5 conflicts with symfony/console v3.2.12.
    - symfony/yaml v5.1.5 conflicts with symfony/console v3.2.11.
    - symfony/yaml v5.1.5 conflicts with symfony/console v3.2.10.
    - symfony/yaml v5.1.5 conflicts with symfony/console v3.2.9.
    - symfony/yaml v5.1.5 conflicts with symfony/console v3.2.8.
    - symfony/yaml v5.1.5 conflicts with symfony/console v3.2.7.
    - symfony/yaml v5.1.5 conflicts with symfony/console v3.2.6.
    - symfony/yaml v5.1.5 conflicts with symfony/console v3.2.5.
    - symfony/yaml v5.1.5 conflicts with symfony/console v3.2.4.
    - symfony/yaml v5.1.5 conflicts with symfony/console v3.2.3.
    - symfony/yaml v5.1.5 conflicts with symfony/console v3.2.2.
    - symfony/yaml v5.1.5 conflicts with symfony/console v3.2.1.
    - symfony/yaml v5.1.5 conflicts with symfony/console v3.2.0.
    - symfony/yaml v5.1.5 conflicts with symfony/console v3.1.10.
    - symfony/yaml v5.1.5 conflicts with symfony/console v3.1.9.
    - symfony/yaml v5.1.5 conflicts with symfony/console v3.1.8.
    - symfony/yaml v5.1.5 conflicts with symfony/console v3.1.7.
    - symfony/yaml v5.1.5 conflicts with symfony/console v3.1.6.
    - symfony/yaml v5.1.5 conflicts with symfony/console v3.1.5.
    - symfony/yaml v5.1.5 conflicts with symfony/console v3.1.4.
    - symfony/yaml v5.1.5 conflicts with symfony/console v3.1.3.
    - symfony/yaml v5.1.5 conflicts with symfony/console v3.1.2.
    - symfony/yaml v5.1.5 conflicts with symfony/console v3.1.1.
    - symfony/yaml v5.1.5 conflicts with symfony/console v3.1.0.
    - symfony/yaml v5.1.5 conflicts with symfony/console v3.0.9.
    - symfony/yaml v5.1.5 conflicts with symfony/console v3.0.8.
    - symfony/yaml v5.1.5 conflicts with symfony/console v3.0.7.
    - symfony/yaml v5.1.5 conflicts with symfony/console v3.0.6.
    - symfony/yaml v5.1.5 conflicts with symfony/console v3.0.5.
    - symfony/yaml v5.1.5 conflicts with symfony/console v3.0.4.
    - symfony/yaml v5.1.5 conflicts with symfony/console v3.0.3.
    - symfony/yaml v5.1.5 conflicts with symfony/console v3.0.2.
    - symfony/yaml v5.1.5 conflicts with symfony/console v3.0.1.
    - symfony/yaml v5.1.5 conflicts with symfony/console v3.0.0.
    - deployer/deployer v6.8.0 requires deployer/phar-update ~2.2 -> satisfiable by deployer/phar-update[v2.2.0].
    - deployer/deployer v6.8.0 requires symfony/yaml ~2.7|~3.0|~4.0|~5.0 -> satisfiable by symfony/yaml[v5.1.5].
    - deployer/deployer is locked to version v6.8.0 and an update of this package was not requested.

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

**Comment by torunar** [comment]
Couldn't reproduce.

**Comment by harm-smits** [comment]
@torunar The SDK currently does not support composer 2.0, there is a PR (#6) for this, but it was ever picked up. So perhaps check if you are using composer v2.
